### ISSUE TITLE
Controls invisible on light colored album covers

### ISSUE THREAD

**Issue by nkijak** [jmowbray/rdio-remote#1]
![screen shot 2015-04-28 at 8 22 54 am](https://cloud.githubusercontent.com/assets/601071/7369428/f28759b0-ed7f-11e4-9a53-128397ffdfc1.png)

Perhaps a gradient overlay at the top would help.

**Comment by jmowbray** [comment]
It wasn't the intention to ever have the controls over top of the album art. For whatever reason, I didn't see that behavior until installing it on a new machine, so that was addressed in commit 10b5dcb4eba34d118177df9b81246565ab6c76e9.

Although... I do like the look of having the album art the entire background. Maybe something to experiment with.
